Missing translation and localization update
nowalor/dismantler pull request #482
Opened 2024-12-17 17:59 UTC by Niracash

Updated localization translation script to automate whole website to translate without problem.

Updates:
- Fixed a bug where FAQ arrays were not translating
- Added new parts name in english
- Updated script to translate whole website (Homepage, parts, FAQ) with command `php artisan localization:translate`

2024-12-18 13:48 UTC, nowalor requested changes
Good job just coming up with a working solution and doing it so fast, of course since it's a review I mostly focus on the stuff that can be better but it's awesome what you have done. 

It's a bit hard reviewing it now since I didn't get a chance to review the initial feature. Here is one thought I had.

Instead of making the script dynamic for both PHP arrays and JSON couldn't it have been better to just decide on what structure fits better and stick with that?

2024-12-18 13:48 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
Please use a config file and don't read variables directly from env

2024-12-18 13:48 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
>          $targetLangs = [
Maybe consider using an enum for this, much cleaner imo

2024-12-18 13:48 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
> +        $client = new Client(['base_uri' => 'https://api-free.deepl.com/v2/']);
Please read the api url from and env variable and a config file. Also consider creating the client in the constructor

2024-12-18 13:48 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
> +    protected function translateJsonFile($sourceLang, $targetLangs, $client, $apiKey)
much nicer to type hint all arguments and return types in modern PHP

2024-12-18 13:48 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
> +        $sourceArray = require $sourcePath;
Not sure about require it's very old school PHP, can you use the file helper or something to read the file?

2024-12-19 12:30 UTC, Niracash commented on app/Console/Commands/TranslateLocalizationFiles.php
> +        $sourceLang = 'en';
I put it in config file if that is ok?

2024-12-19 13:19 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
> +        $sourceLang = 'en';
don't think it needs to be in the config

2024-12-20 12:29 UTC, nowalor approved these changes
Much fewer and more minor comments that last time, it's looking pretty good. If you fix everything you can merge and deploy it yourself :)

2024-12-20 12:29 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
> +        $this->sourceLang = config('deepl.source_language', 'en');
Would make more sense to do in the constructor

2024-12-20 12:29 UTC, nowalor commented on app/Console/Commands/TranslateLocalizationFiles.php
> +        $apiKey = config('deepl.key');
should be a class variable and set in the constructor

2024-12-20 12:29 UTC, nowalor commented on config/deepl.php
> +    'target_languages' => [
not normally what you would use a config for, it's only for api urls and keys and such. I get that you use these in the request but if you think about it they are also the website languages and we might want to use them in various places not just when dealing with the deepL API.

So WebsiteLocaleEnum.php would feel more fitting. I also see you are already refactoring to en Enum based on our slack convo but still seems like the comments could be helpful :)

2024-12-20 12:29 UTC, nowalor commented on config/deepl.php
> +    'source_language' => env('DEEPL_SOURCE_LANG', 'en'),
Does not need to be a config variable imo, after you have switched to an enum for the localization variables just set source lang in the command to be able to LocaleEnum::EN->value or something like that

2024-12-20 12:29 UTC, nowalor commented on config/deepl.php
> +<?php
I normally just put these in services.php, no need to create a new class

2024-12-20 12:29 UTC, nowalor commented on app/Enums/TargetLanguages.php
> +    public static function getLanguages(): array
Alternative that I have used to do a similar thing before,
 ```
   public static function values(): array
    {
        return array_map(fn ($case) => $case->value, self::cases());
    }
```

2024-12-20 20:27 UTC, merged